services:

  software-security-service:
    container_name: software-security-service
    restart: unless-stopped
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Host=user-postgres;Port=5432;Database=software_security;Username=postgres;Password=1;Timezone=Europe/Minsk;
    depends_on:
      - postgres


  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: software_security
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: